/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WitnessRouteImport } from './routes/witness'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewRouteImport } from './routes/new'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PactsPactIdRouteImport } from './routes/pacts.$pactId'
import { Route as PactsPactIdSettleRouteImport } from './routes/pacts.$pactId.settle'

const WitnessRoute = WitnessRouteImport.update({
  id: '/witness',
  path: '/witness',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PactsPactIdRoute = PactsPactIdRouteImport.update({
  id: '/pacts/$pactId',
  path: '/pacts/$pactId',
  getParentRoute: () => rootRouteImport,
} as any)
const PactsPactIdSettleRoute = PactsPactIdSettleRouteImport.update({
  id: '/settle',
  path: '/settle',
  getParentRoute: () => PactsPactIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/witness': typeof WitnessRoute
  '/pacts/$pactId': typeof PactsPactIdRouteWithChildren
  '/pacts/$pactId/settle': typeof PactsPactIdSettleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/witness': typeof WitnessRoute
  '/pacts/$pactId': typeof PactsPactIdRouteWithChildren
  '/pacts/$pactId/settle': typeof PactsPactIdSettleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/witness': typeof WitnessRoute
  '/pacts/$pactId': typeof PactsPactIdRouteWithChildren
  '/pacts/$pactId/settle': typeof PactsPactIdSettleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/new'
    | '/profile'
    | '/witness'
    | '/pacts/$pactId'
    | '/pacts/$pactId/settle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/new'
    | '/profile'
    | '/witness'
    | '/pacts/$pactId'
    | '/pacts/$pactId/settle'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/profile'
    | '/witness'
    | '/pacts/$pactId'
    | '/pacts/$pactId/settle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  ProfileRoute: typeof ProfileRoute
  WitnessRoute: typeof WitnessRoute
  PactsPactIdRoute: typeof PactsPactIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/witness': {
      id: '/witness'
      path: '/witness'
      fullPath: '/witness'
      preLoaderRoute: typeof WitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacts/$pactId': {
      id: '/pacts/$pactId'
      path: '/pacts/$pactId'
      fullPath: '/pacts/$pactId'
      preLoaderRoute: typeof PactsPactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacts/$pactId/settle': {
      id: '/pacts/$pactId/settle'
      path: '/settle'
      fullPath: '/pacts/$pactId/settle'
      preLoaderRoute: typeof PactsPactIdSettleRouteImport
      parentRoute: typeof PactsPactIdRoute
    }
  }
}

interface PactsPactIdRouteChildren {
  PactsPactIdSettleRoute: typeof PactsPactIdSettleRoute
}

const PactsPactIdRouteChildren: PactsPactIdRouteChildren = {
  PactsPactIdSettleRoute: PactsPactIdSettleRoute,
}

const PactsPactIdRouteWithChildren = PactsPactIdRoute._addFileChildren(
  PactsPactIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  ProfileRoute: ProfileRoute,
  WitnessRoute: WitnessRoute,
  PactsPactIdRoute: PactsPactIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
